name: Build on Merge

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Clean up previous build
        run: rm -rf dist

      - name: Build library
        run: npm run build-library

      - name: Build docs
        run: npm run build-docs

      - name: Commit build files
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"
          git add dist
          git commit -m "Add built files"
          git push
